#!/bin/bash

# daily Prod job runs at 06:35 UTC or thereabouts.
# Was: run the Stage job three times a day, on the hours 16, 20, and 00 UTC.
# Now: run the Stage job once a day, on the hour 09 UTC.


case $(date -u +%H) in
  09) 
	;;
   *)
      exit 0 
	;;
esac

RECIPIENTS="sync-core@mozilla.com"


# echo "Testing automated delivery of TPS Stage failures." | HOME=/home/ubuntu mailx -s 'Testing TPS Stage mail' $RECIPIENTS
# exit 2

sudo -u ubuntu -i -- bash -c "(cd /home/ubuntu/Library/github/mozilla-services/sync-tps-setup && make update && make nightly && make stage) >& /tmp/stage-results.txt" 

STATUS=$?

echo "Exit status is $STATUS." > /tmp/last-stage-status.txt

if [ $STATUS = "0" ]; then
	 echo "TPS Stage run succeeded." | HOME=/home/ubuntu mailx -s 'TPS Stage Success' $RECIPIENTS	
else
	sed -e '1,/^Test Summary/d' < /tmp/stage-results.txt > /tmp/stage-summary.txt
	echo -e "\n\nDetails in the attachment." >> /tmp/stage-summary.txt
	HOME=/home/ubuntu mailx -a /tmp/stage-results.txt -s 'TPS Stage failure' $RECIPIENTS < /tmp/stage-summary.txt
fi
