#!/bin/bash

RECIPIENTS="sync-core@mozilla.com"

# echo "Testing automated delivery of TPS failures." | HOME=/home/ubuntu mailx -s 'Testing TPS mail' $RECIPIENTS

sudo -u ubuntu -i -- bash -c "(cd /home/ubuntu/Library/github/mozilla-services/sync-tps-setup && make update && make nightly && make prod) >& /tmp/results.txt" 

if [ $? = "0" ]; then
	echo "TPS Prod succeeded; log in and view /tmp/results.txt for details." | HOME=/home/ubuntu mailx -s 'TPS success' $RECIPIENTS
else
        sed -e '1,/^Test summary/d' < /tmp/results.txt > /tmp/results-summary.txt
	HOME=/home/ubuntu mailx -s 'TPS failure' $RECIPIENTS < /tmp/results-summary.txt
fi
